# Generated by Django 4.1.7 on 2023-04-15 18:23

import codio_auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codio_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', codio_auth.models.CodioUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
